%----------------------PROPRIETA'  SVD-----------------


% A = USV'


%1. CALCOLA RANGO MATRICE (COINCIDE CON NUMERO DI VALORI SINGOLARI NON
%NULLI)
%2. CALCOLA CONDIZIONAMENTO MATRICE (K = Smax/Smin) con Smin diverso da 0
%3. RISOLUZIONE SISTEMA DETERMINATO, SOVRADET. E SOTTODET. E MAL
%CONDIZIONATI



%ALTRE PROPRIETA'
%1. AUTOVALORI L di A'A SONO CALCOLABILI COME L = s^2 e AUTOVETTORI SONO
%SULLE COLONNE DI V

%2. AUTOVALORI L di AA' SONO CALCOLABILI COME L = s^2 e AUTOVETTORI SONO
%SULLE COLONNE DI U

%3. SE A QUADRATA ALLORA I VALORI SINGOLARI (s) SONO PROPRIO AUTOVALORI
%DELLA MATRICE

%4. LE COLONNE DA U(0) A U(R) (Minimo termine non nullo) FORMANO BASE
%ORTONORMALE DELLA IMMAGINE DI A MENTRE DA U(R+1) A U(N) FORMANO BASE
%ORTONORMALE DEL NUCLEO DI A-TRASPOSTA

%5. LE COLONNE DA V(0) A V(R) (Minimo termine non nullo) FORMANO BASE
%ORTONORMALE DELLA IMMAGINE DI A-TRASPOSTA MENTRE DA V(R+1) A V(N) FORMANO BASE
%ORTONORMALE DEL NUCLEO DI A


% S ha questa forma dove R rappresenta ultimo numero non nullo
[4 0 0 0 0;
 0 2 0 0 0;
 0 0 1 0 0;
 0 0 0 0 0;
 0 0 0 0 0]
 
R = 3 %QUINDI RANGO DELLA MATRICE A (CHE E' STATA DECOMPOSTA E' 3)